export * from './base.model';
export * from './base-popup.service';
export * from './base.service';
export * from './base-dialog.component';
export * from './base-delete-dialog.component';
export * from './base-detail.component';
export * from './base.component';
export * from './base.route';
export * from './fab-add-base/fab-add-base.component'
